import tkinter as tk
import random
import turtle

root = tk.Tk()
t = turtle.Turtle()
root.geometry("500x500")
def e():
    t.shape("arrow")
    t.speed(1)
    t.forward(100)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(250)
    t.right(45)
    t.forward(25)
    t.right(45)
    t.forward(100)
    t.right(135)
    t.forward(25)
    t.penup()
    t.right(180)
    t.forward(25)
    t.right(135)
    t.pendown()
    t.forward(50)
    t.right(45)
    t.forward(25)
    t.penup()
    t.left(45)
    t.forward(50)
    t.left(135)
    t.pendown()
    t.forward(25)
    t.left(135)
    t.forward(50)
    t.left(45)
    t.forward(25)
    t.left(135)
butonE  = tk.Button(root, text="E", command=e)
butonE.pack()
turtle.bgcolor("aquamarine")
t.pencolor("red")
t.fillcolor("pink")
t.penup()
t.pendown()
t.begin_fill()
t.end_fill()
turtle.exitonclick()
turtle.bgcolor("black")      
root.mainloop()