import tkinter as tk

anapencere = tk.Tk()
çerçeve1 = tk.Frame(anapencere)
çerçeve2 = tk.Frame(anapencere)

kümes_e = tk.Label(çerçeve1, text="Kümes")
kümes_e.grid(row=0, column=0)
yas_e = tk.Label(çerçeve1, text="Yaş")
yas_e.grid(row=1,column=0)
hs_e = tk.Label(çerçeve1, text="Hayvan\nSayısı")
hs_e.grid(row=3,column=0)
go_e = tk.Label(çerçeve1, text="Günlük\nÖlü")
go_e.grid(row=4,column=0)
su_e = tk.Label(çerçeve1, text="Su\n(Ton)")
su_e.grid(row=5,column=0)

k_1_e = tk.Label(çerçeve1, text="K-1")
k_1_e.grid(row=0, column=1)
yask_1_g = tk.Entry(çerçeve1, width="10")
yask_1_g.grid(row=1, column=1)
hs_k1g = tk.Entry(çerçeve1, width="10")
hs_k1g.grid(row=3,column=1)
gok1g = tk.Entry(çerçeve1,width="10")
gok1g.grid(row=4,column=1)
suk1g = tk.Entry(çerçeve1,width="10")
suk1g.grid(row=5,column=1)

k_2_e = tk.Label(çerçeve1, text="K-2")
k_2_e.grid(row=0,column=2)
yask_2_g = tk.Entry(çerçeve1, width="10")
yask_2_g.grid(row=1, column=2)
hs_k2g = tk.Entry(çerçeve1, width="10")
hs_k2g.grid(row=3,column=2)
gok2g = tk.Entry(çerçeve1,width="10")
gok2g.grid(row=4,column=2)
suk2g = tk.Entry(çerçeve1,width="10")
suk2g.grid(row=5,column=2)


k_3_e = tk.Label(çerçeve1, text="K-3")
k_3_e.grid(row=0,column=3)
yask_3_g = tk.Entry(çerçeve1, width="10")
yask_3_g.grid(row=1, column=3)
hs_k3g = tk.Entry(çerçeve1, width="10")
hs_k3g.grid(row=3,column=3)
gok3g = tk.Entry(çerçeve1,width="10")
gok3g.grid(row=4,column=3)
suk3g = tk.Entry(çerçeve1,width="10")
suk3g.grid(row=5,column=3)


k_4_e = tk.Label(çerçeve1, text="K-4")
k_4_e.grid(row=0,column=4)
yask_4_g = tk.Entry(çerçeve1, width="10")
yask_4_g.grid(row=1, column=4)
hs_k4g = tk.Entry(çerçeve1, width="10")
hs_k4g.grid(row=3,column=4)
gok4g = tk.Entry(çerçeve1,width="10")
gok4g.grid(row=4,column=4)
suk4g = tk.Entry(çerçeve1,width="10")
suk4g.grid(row=5,column=4)


k_5_e = tk.Label(çerçeve1, text="K-5")
k_5_e.grid(row=0, column=5)
yask_5_g = tk.Entry(çerçeve1, width="10")
yask_5_g.grid(row=1, column=5)
hs_k5g = tk.Entry(çerçeve1, width="10")
hs_k5g.grid(row=3,column=5)
gok5g = tk.Entry(çerçeve1,width="10")
gok5g.grid(row=4,column=5)
suk5g = tk.Entry(çerçeve1,width="10")
suk5g.grid(row=5,column=5)

k_6_e = tk.Label(çerçeve1, text="K-6")
k_6_e.grid(row=0,column=6)
yask_6_g = tk.Entry(çerçeve1, width="10")
yask_6_g.grid(row=1, column=6)
hs_k6g = tk.Entry(çerçeve1, width="10")
hs_k6g.grid(row=3,column=6)
gok6g = tk.Entry(çerçeve1,width="10")
gok6g.grid(row=4,column=6)
suk6g = tk.Entry(çerçeve1,width="10")
suk6g.grid(row=5,column=6)


k_7_e = tk.Label(çerçeve1,text="K-7")
k_7_e.grid(row=0, column=7)
yask_7_g = tk.Entry(çerçeve1, width="10")
yask_7_g.grid(row=1, column=7)
hs_k7g = tk.Entry(çerçeve1, width="10")
hs_k7g.grid(row=3,column=7)
gok7g = tk.Entry(çerçeve1,width="10")
gok7g.grid(row=4,column=7)
suk7g = tk.Entry(çerçeve1,width="10")
suk7g.grid(row=5,column=7)


tarih_e = tk.Label(çerçeve2, text="Tarih")
tarih_e.grid(row=0,column=0,padx=20,pady=20)
tasnif_yumurta_e = tk.Label(çerçeve2, text="Tasnif Yumurta\n(Koli)")
tasnif_yumurta_e.grid(row=1,column=0)



çerçeve1.pack(padx=10,pady=10,side="left")
çerçeve2.pack(padx=10,pady=10,side="right")
anapencere.mainloop()