import tkinter as tk
import time
from PIL import Image, ImageTk, ImageGrab

anapencere = tk.Tk()
anapencere.title("Kümes Kayıt Ekranı ")
çerçeve1 = tk.Frame(anapencere)
çerçeve2 = tk.Frame(anapencere)
çerçeve3 = tk.Frame(anapencere)
kümes_e = tk.Label(çerçeve1, text="Kümes",background="lightgreen",width="10",height="2")
kümes_e.grid(row=0, column=0)
yas_e = tk.Label(çerçeve1, text="Yaş",background="pink",width="10")
yas_e.grid(row=1,column=0)
hs_e = tk.Label(çerçeve1, text="Hayvan Sayısı",background="lightgreen",width="10")
hs_e.grid(row=3,column=0)
go_e = tk.Label(çerçeve1, text="Günlük Ölü",background="pink",width="10")
go_e.grid(row=4,column=0)
su_e = tk.Label(çerçeve1, text="Su (Ton)",background="lightgreen",width="10")
su_e.grid(row=5,column=0)
kanli_e = tk.Label(çerçeve1,text="Kanlı (Adet)",background="pink",width="10")
kanli_e.grid(row=6,column=0)
kirli_e = tk.Label(çerçeve1,text="Kanlı (Viyol)",background="lightgreen",width="10")
kirli_e.grid(row=7,column=0)
kirik_e = tk.Label(çerçeve1,text="Kırık (Viyol)",background="pink",width="10")
kirik_e.grid(row=8,column=0)
randiman_e = tk.Label(çerçeve1,text="Randıman (%)",background="lightgreen",width="10")
randiman_e.grid(row=9,column=0)


k_1_e = tk.Label(çerçeve1, text="K-1", background="yellow",width="10",height="2")
k_1_e.grid(row=0, column=1)
yask_1_g = tk.Entry(çerçeve1, width="10")
yask_1_g.grid(row=1, column=1)
hs_k1g = tk.Entry(çerçeve1, width="10")
hs_k1g.grid(row=3,column=1)
gok1g = tk.Entry(çerçeve1,width="10")
gok1g.grid(row=4,column=1)
suk1g = tk.Entry(çerçeve1,width="10")
suk1g.grid(row=5,column=1)
kanli1g = tk.Entry(çerçeve1,width="10")
kanli1g.grid(row=6,column=1)
kirli1kg = tk.Entry(çerçeve1,width="10")
kirli1kg.grid(row=7,column=1)
kirik1kg = tk.Entry(çerçeve1,width="10")
kirik1kg.grid(row=8,column=1)

k_2_e = tk.Label(çerçeve1, text="K-2", background="yellow",width="10",height="2")
k_2_e.grid(row=0,column=2)
yask_2_g = tk.Entry(çerçeve1, width="10")
yask_2_g.grid(row=1, column=2)
hs_k2g = tk.Entry(çerçeve1, width="10")
hs_k2g.grid(row=3,column=2)
gok2g = tk.Entry(çerçeve1,width="10")
gok2g.grid(row=4,column=2)
suk2g = tk.Entry(çerçeve1,width="10")
suk2g.grid(row=5,column=2)
kanli2g = tk.Entry(çerçeve1,width="10")
kanli2g.grid(row=6,column=2)
kirli2kg = tk.Entry(çerçeve1,width="10")
kirli2kg.grid(row=7,column=2)
kirik2kg = tk.Entry(çerçeve1,width="10")
kirik2kg.grid(row=8,column=2)


k_3_e = tk.Label(çerçeve1, text="K-3", background="yellow",width="10",height="2")
k_3_e.grid(row=0,column=3)
yask_3_g = tk.Entry(çerçeve1, width="10")
yask_3_g.grid(row=1, column=3)
hs_k3g = tk.Entry(çerçeve1, width="10")
hs_k3g.grid(row=3,column=3)
gok3g = tk.Entry(çerçeve1,width="10")
gok3g.grid(row=4,column=3)
suk3g = tk.Entry(çerçeve1,width="10")
suk3g.grid(row=5,column=3)
kanli3g = tk.Entry(çerçeve1,width="10")
kanli3g.grid(row=6,column=3)
kirli3kg = tk.Entry(çerçeve1,width="10")
kirli3kg.grid(row=7,column=3)
kirik3kg = tk.Entry(çerçeve1,width="10")
kirik3kg.grid(row=8,column=3)

k_4_e = tk.Label(çerçeve1, text="K-4", background="yellow",width="10",height="2")
k_4_e.grid(row=0,column=4)
yask_4_g = tk.Entry(çerçeve1, width="10")
yask_4_g.grid(row=1, column=4)
hs_k4g = tk.Entry(çerçeve1, width="10")
hs_k4g.grid(row=3,column=4)
gok4g = tk.Entry(çerçeve1,width="10")
gok4g.grid(row=4,column=4)
suk4g = tk.Entry(çerçeve1,width="10")
suk4g.grid(row=5,column=4)
kanli4g = tk.Entry(çerçeve1,width="10")
kanli4g.grid(row=6,column=4)
kirli4kg = tk.Entry(çerçeve1,width="10")
kirli4kg.grid(row=7,column=4)
kirik4kg = tk.Entry(çerçeve1,width="10")
kirik4kg.grid(row=8,column=4)

k_5_e = tk.Label(çerçeve1, text="K-5", background="yellow",width="10",height="2")
k_5_e.grid(row=0, column=5)
yask_5_g = tk.Entry(çerçeve1, width="10")
yask_5_g.grid(row=1, column=5)
hs_k5g = tk.Entry(çerçeve1, width="10")
hs_k5g.grid(row=3,column=5)
gok5g = tk.Entry(çerçeve1,width="10")
gok5g.grid(row=4,column=5)
suk5g = tk.Entry(çerçeve1,width="10")
suk5g.grid(row=5,column=5)
kanli5g = tk.Entry(çerçeve1,width="10")
kanli5g.grid(row=6,column=5)
kirli5kg = tk.Entry(çerçeve1,width="10")
kirli5kg.grid(row=7,column=5)
kirik5kg = tk.Entry(çerçeve1,width="10")
kirik5kg.grid(row=8,column=5)

k_6_e = tk.Label(çerçeve1, text="K-6", background="yellow",width="10",height="2")
k_6_e.grid(row=0,column=6)
yask_6_g = tk.Entry(çerçeve1, width="10")
yask_6_g.grid(row=1, column=6)
hs_k6g = tk.Entry(çerçeve1, width="10")
hs_k6g.grid(row=3,column=6)
gok6g = tk.Entry(çerçeve1,width="10")
gok6g.grid(row=4,column=6)
suk6g = tk.Entry(çerçeve1,width="10")
suk6g.grid(row=5,column=6)
kanli6g = tk.Entry(çerçeve1,width="10")
kanli6g.grid(row=6,column=6)
kirli6kg = tk.Entry(çerçeve1,width="10")
kirli6kg.grid(row=7,column=6)
kirik6kg = tk.Entry(çerçeve1,width="10")
kirik6kg.grid(row=8,column=6)

k_7_e = tk.Label(çerçeve1,text="K-7", background="yellow",width="10",height="2")
k_7_e.grid(row=0, column=7)
yask_7_g = tk.Entry(çerçeve1, width="10")
yask_7_g.grid(row=1, column=7)
hs_k7g = tk.Entry(çerçeve1, width="10")
hs_k7g.grid(row=3,column=7)
gok7g = tk.Entry(çerçeve1,width="10")
gok7g.grid(row=4,column=7)
suk7g = tk.Entry(çerçeve1,width="10")
suk7g.grid(row=5,column=7)
kanli7g = tk.Entry(çerçeve1,width="10")
kanli7g.grid(row=6,column=7)
kirli7kg = tk.Entry(çerçeve1,width="10")
kirli7kg.grid(row=7,column=7)
kirik7kg = tk.Entry(çerçeve1,width="10")
kirik7kg.grid(row=8,column=7)

tarih_label = tk.Label(çerçeve2, font='Verdena', fg='black') 
tarih_label.grid(row=0,column=1)
def digital_clock(): 
    time_live = time.strftime("%d/%m/%Y")
    tarih_label.config(text=time_live,background="aquamarine") 
    tarih_label.after(100, digital_clock)
digital_clock()


tarih_e = tk.Label(çerçeve2, text="Tarih:",background="aquamarine",width="10")
tarih_e.grid(row=0,column=0)


çiftsari_e =tk.Label(çerçeve2,text="Çift Sarı",background="lightgreen",width="10")
çiftsari_e.grid(row=1,column=0)
çiftsari_g = tk.Entry(çerçeve2,width="8")
çiftsari_g.grid(row=1,column=1)


xl_e =tk.Label(çerçeve2,text="XL",background="pink",width="10")
xl_e.grid(row=2,column=0)
xl_g = tk.Entry(çerçeve2,width="8")
xl_g.grid(row=2,column=1)

l_e =tk.Label(çerçeve2,text="L",background="lightgreen",width="10")
l_e.grid(row=3,column=0)
l_g = tk.Entry(çerçeve2,width="8")
l_g.grid(row=3,column=1)


m_e =tk.Label(çerçeve2,text="M",background="pink",width="10")
m_e.grid(row=4,column=0)
m_g = tk.Entry(çerçeve2,width="8")
m_g.grid(row=4,column=1)


s_e =tk.Label(çerçeve2,text="S",background="lightgreen",width="10")
s_e.grid(row=5,column=0)
s_g = tk.Entry(çerçeve2,width="8")
s_g.grid(row=5,column=1)

tsnfdisi_e =tk.Label(çerçeve2,text="Tasnif Dışı",background="pink",width="10")
tsnfdisi_e.grid(row=6,column=0)
tsnfdisi_g = tk.Entry(çerçeve2,width="8")
tsnfdisi_g.grid(row=6,column=1)

saglam_e =tk.Label(çerçeve2,text="Sağlam",background="lightgreen",width="10")
saglam_e.grid(row=7,column=0)
saglam_g = tk.Entry(çerçeve2,width="8")
saglam_g.grid(row=7,column=1)


kirli_sag_e =tk.Label(çerçeve2,text="Kirli",background="pink",width="10")
kirli_sag_e.grid(row=8,column=0)
kirli_sag_g = tk.Entry(çerçeve2,width="8")
kirli_sag_g.grid(row=8,column=1)

kirik_sag_e =tk.Label(çerçeve2,text="Kırık",background="lightgreen",width="10")
kirik_sag_e.grid(row=9,column=0)
kirik_sag_g = tk.Entry(çerçeve2,width="8")
kirik_sag_g.grid(row=9,column=1)

yarka_e =tk.Label(çerçeve2,text="Yarka",background="pink",width="10")
yarka_e.grid(row=10,column=0)
yarka_g = tk.Entry(çerçeve2,width="8")
yarka_g.grid(row=10,column=1)

toplam_e =tk.Label(çerçeve2,text="Toplam",background="lightgreen",width="10")
toplam_e.grid(row=11,column=0)
saglam_var = tk.IntVar()
kirli_var = tk.IntVar()
kirik_var = tk.IntVar()
yarka_var = tk.IntVar()
saglam_var = saglam_g.get()
kirli_var = kirli_sag_g.get()
kirik_var = kirik_sag_g.get()
yarka_var = yarka_g.get()

def toplam_func():
    total = saglam_var + kirli_var + kirik_var + yarka_var
    total_e = tk.Label(çerçeve2,text=total)
    total_e.grid(row=11,column=1)
topla_butonu = tk.Button(çerçeve3, text="Topla",command=toplam_func)
topla_butonu.pack(side="right")



imzaimage = tk.PhotoImage(file="ercancagimza.png")
image2=Image.open('caglayan.png')
boyutluimage2 = image2.resize((270,65))
my_img=ImageTk.PhotoImage(boyutluimage2)
kanvas = tk.Canvas(çerçeve3, height=70, width=250)
kanvas.create_image(135, 40, image=imzaimage)
kanvas.pack(padx=1, pady=1,side='left')
kanvas2 = tk.Canvas(çerçeve3, height=80, width=300)
kanvas2.create_image(155, 40, image=my_img)
kanvas2.pack(padx=1, pady=1, side="right")

çerçeve3.pack(padx=10,pady=10,side= 'bottom')
çerçeve1.pack(padx=10,pady=10,side="left")
çerçeve2.pack(padx=10,pady=10,side="right")

anapencere.mainloop()